name: Docker ibmlearner_translation_app Image CI

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.JINX_BOHR }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/camparchimedes/ibmlearner_translation_app:latest
          registry: ghcr.io
          username: camparchimedes
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if logged in
        run: |
          github-cli whoami


