name: Docker ibmlearner_translation_app Image CI
run-name: ${{ github.actor }} is pushing it
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        env:
          JINX_BOHR: ${{ secrets.JINX_BOHR }}
        
      - name: Push Docker image
        run: |
            echo $JINX_BOHR | docker login ghcr.io -u camparchimedes --password-stdin 
            docker push ghcr.io/camparchimedes/ibmlearner_translation_app:latest
        
        
