name: Docker ibmlearner_translation_app Image CI
run-name: ${{ github.actor }} is pushing it
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: echo "ghcr.io ${{ secrets.JINX_BOHR }}" | docker login ghcr.io -u camparchimedes --password-stdin
      - name: Build and push Docker image
        run: docker push ghcr.io/camparchimedes/ibmlearner_translation_app:latest
        
